version: '3'
services:
  mongo:
    container_name: magnetcrawler_db
    image: mongo
    ports:
     - "127.0.0.1:27017:27017"
    volumes:
     - ./data/mongo:/data/db
  redis:
    container_name: magnetcrawler_redis
    image: redis
    ports:
     - "127.0.0.1:6379:6379"
    volumes:
     - ./data/redis:/data

